### ISSUE TITLE
Pulse has been down for several hours - DNS record is gone.

### ISSUE THREAD

**Issue by Serubin** [maplemedia/pulse-sms-issues#1036]
DNS records have been removed for pulsesms.app. This has been occurring for several hours today. 

Tagging @mohsintahir as he's been committing to https://github.com/maplemedia/pulse-sms-web

**Comment by inferno493** [comment]
Mine is still working, but my pc app only displays new messages in a popup. I can't open them or reply on pc or login to the web app.

**Comment by Serubin** [comment]
@inferno493 If you reload the PC app, it will fail. 

`1.1.1.1` and `8.8.8.8` do not have this record. Pulse was recently moved to AWS - I wonder if they tried to move DNS to AWS or some other service and it failed.

**Comment by athompson673** [comment]
Just here to confirm also `8844` no record, and to ping @klinker24 too

**Comment by inferno493** [comment]
I uninstalled then reinstalled. App still working but only with background popup messages as before.

**Comment by athompson673** [comment]
@inferno493 windows may have cached IP still. ICANN says the domain registration was updated "2020-11-17 19:27:46 UTC" (8 ish hours ago) I tired this: https://developers.google.com/speed/public-dns/cache, which didn't seem to do much.

**Comment by mohsintahir** [comment]
Hi guys,

This issue was due to some domain transfer issue. I will fix it soon.
Thanks!

**Comment by blackjackshellac** [comment]
ditto, on linux desktop the journal log is being spammed with this kind of exception error (about 2-5 times per second),

```
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]: (node:36934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. Thi>
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at Object.onMessage (electron/js2c/renderer_init.js:2395:16)
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at EventEmitter.emit (events.js:203:13)
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:2619:9)
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at new Promise (<anonymous>)
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at electron/js2c/renderer_init.js:2619:40
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at electron/js2c/renderer_init.js:2988:43
Nov 18 06:31:23 woot.home pulse-sms.desktop[36934]:     at WebFrame../lib/renderer/api/web-frame.ts.WebFrame.<computed> [as execute>
```
The app wouldn't exit normally, but this fixed it,

```
$ killall pulse-sms
```

Hopefully the DNS issues are resolved soon, good luck.

**Comment by klinker24** [comment]
They know about it. I don't know what the timeline to fix is. Issue transferring some DNS records. No platforms or services will work until it is resolved.

No reason to tag me, I don't own Pulse anymore.

**Comment by tedtms** [comment]
Is the entire domain being transferred? klinkerapps.com and all of its subdomains are no longer resolving.

**Comment by blackjackshellac** [comment]
Apparently Luke Klinker has sold up, seems he commented and then deleted his comment,

```
They know about it. I don't know what the timeline to fix is. Issue transferring some DNS records. No platforms or services will work until it is resolved.

No reason to tag me, I don't own Pulse anymore.
```

Not sure I find comfort in that.

**Comment by blackjackshellac** [comment]
Okay, I'm out,

https://www.androidpolice.com/2020/10/29/it-looks-like-pulse-sms-has-been-bought-by-maple-media-get-ready-for-intrusive-ads/

**Comment by mohsintahir** [comment]
Most of the application should be working now.

**Comment by mohsintahir** [comment]
I think every subdomain and app is running now. Despite that, it will still not be reachable in certain regions yet as DNS  propagation takes time. Pardon me for inconvenience. I am closing this issue.

**Comment by tedtms** [comment]
FWIW the DNS issues appear to be resolved on my end. App is opening and displaying without issue on Linux now.
