### ISSUE TITLE
Pulse SMS Desktop App Does Not Load Content

### ISSUE THREAD

**Issue by DavidCao22** [maplemedia/pulse-sms-issues#1045]
## Confirm this Issue
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** HP Envy Laptop on Windows 10, 
**Primary device:** Pixel 4 on Android 11
**App version:** Desktop app v4.3.0

## Describe the Bug

The desktop app is not loading the app at all. It just loads a Cloudflare HTTP message. No controls, settings or messages appear. Reloading the app, restarting the app, and re-installing the app do not fix the issue. 

### Steps to Reproduce

1. Try opening the desktop app. It only loads a garbled HTTP message about Cloudflare. (see screenshot)

### Expected Behavior

It should load the desktop app

### Screenshots

![2020-12-26 11_32_52-Pulse SMS](https://user-images.githubusercontent.com/10539139/103156433-2b198700-476e-11eb-8764-4d0dc5843cdb.png)

**Comment by venturamicah** [comment]
I have this same issue.

**Comment by DavidCao22** [comment]
The issue resolved itself for me. Pulse desktop now works. Closing issue.
