### ISSUE TITLE
Web/Desktop: Compose - Contacts Not Appearing

### ISSUE THREAD

**Issue by timothy-eichman-tfs** [maplemedia/pulse-sms-issues#1046]
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the report that you are filing.*

## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Surface Pro 4 and Surface Pro 7 (Both Windows 10 199).  Chrome and Edge browsers and Pulse desktop app
**Primary device:** Samsung S10+ and Samsung S20+
**App version:** (web doesn't indicate version)

## Describe the Bug

Contact list isn’t showing in the dropdown on the Web and Windows apps when starting a new conversation.  

Followed the instructions to resync our contacts per the FAQ and GitHub thread, but still they don’t show up when composing a new message.  I see the contacts in the contacts list, but when we try to start a new conversation, none appear in the dropdown (see screenshot below). 

### Steps to Reproduce

1. Go to Web app or Desktop App
2. Click on Compose
3. Start to type a contact
4. See no contacts listed
5. Click dropdown arrow and what was typed is turned into conversation contact

### Expected Behavior

Expect to see contacts as typing or when clicking dropdown.

### Screenshots

![Pulse SMS Bug 1](https://user-images.githubusercontent.com/59745595/103236867-ffd09c80-4913-11eb-9585-cd40aef41643.png)
![Pulse SMS Bug 2](https://user-images.githubusercontent.com/59745595/103236868-ffd09c80-4913-11eb-99c5-f818c5f99673.png)
![Pulse SMS Bug 3](https://user-images.githubusercontent.com/59745595/103236869-ffd09c80-4913-11eb-9fbe-bd46d9a4df8c.png)

### Additional Information

Followed instructions in FAQ to refresh contacts without success.  Did see previous issue from 2018 but it was closed.  This appears to be new as it was working up until a few days ago (24/DEC/2020).

-Tim Eichman 

(sent email to support with same details [my GitHub account is my work account but the email came from my personal account which is associated with my purchase of Pulse SMS)

**Comment by kthemm** [comment]
I am having the same issue except I'm using a Galaxy S9 and Firefox. I've tried resyncing contacts also.

**Comment by SVIEUVEL** [comment]
J'ai le meme problème avec Huawei P20 Pro et BalckviewBV5500. J'ai tout essayé avec IE, EDGE, CHROME, FIREFOX etc... toujours pareil

**Comment by timothy-eichman-tfs** [comment]
Resolved as of yesterday (04/JAN/2021).
